### ISSUE TITLE
Upgrade to pytables 3.5

### ISSUE THREAD

**Issue by wkerzendorf** [conda-forge/pyne-feedstock#31]
Issue:
Numpy=1.15 is troublesome so I need to upgrade to numpy=1.16 which breaks pytables 3.4.x which is unbroken with pytables 3.5 which pyne does not support. Can we allow this conda package to live with pytables 3.5 as well?

**Comment by scopatz** [comment]
Yep! That's be fine with me.  PRs welcome!

**Comment by wkerzendorf** [comment]
@scopatz the pinned hdf5 disallows upgrade of pytables. are you happy to unpin?

**Comment by wkerzendorf** [comment]
@scopatz what happened. you closed the PR?

**Comment by gonuke** [comment]
This has been resolved by recent activity.
